<a href="https://colab.research.google.com/github/ultrasmartary/MLCollege/blob/master/MLCollege_Day2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8]],dtype=float)
print(a)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


In [2]:
b=np.arange(1,9,1)
b.shape=((2,4))
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [3]:
c=np.zeros((3,3),dtype=int)
print(c)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [4]:
d=np.linspace(1,9,16,endpoint=True,retstep=True)
print(d)

(array([1.        , 1.53333333, 2.06666667, 2.6       , 3.13333333,
       3.66666667, 4.2       , 4.73333333, 5.26666667, 5.8       ,
       6.33333333, 6.86666667, 7.4       , 7.93333333, 8.46666667,
       9.        ]), 0.5333333333333333)


In [5]:
#Random Module has four major functions:
#rand()
#randn()
#ranf()
#randint()
a=np.random.rand(3,4)
print(a)


[[0.36094983 0.23215244 0.0625458  0.85856015]
 [0.32314174 0.56830039 0.35712676 0.60597319]
 [0.28389035 0.24409361 0.1508367  0.22721521]]


In [6]:
b=np.random.randn(5,2)
print(b)

[[-0.95706288  0.21450447]
 [ 0.38902251  1.67409873]
 [-1.27479853 -0.47802096]
 [-1.28764211 -0.75495449]
 [ 0.40699918  0.21609184]]


In [7]:
c=np.random.randint(2,9,size=5)
print(c)

[6 8 5 8 4]


In [8]:
#Attributes of Arrays
#Dimension:ndim
#Shape:shape
#Size:size
#Datatype:dtype
#Itemsize:itemsize
a=np.arange(0,12,1)
a.shape=((3,4))
print('a',a)
print('Dimensions',a.ndim)
print('Shape',a.shape)
print('Size:',a.size)
print('Datatype:',a.dtype)
print('itemsize:',a.itemsize)


a [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Dimensions 2
Shape (3, 4)
Size: 12
Datatype: int64
itemsize: 8


In [9]:
#Indexing And Slicing
b=np.arange(11,20,1)
print(b)
b[-3]

[11 12 13 14 15 16 17 18 19]


17

In [10]:
print(a)
a[-1,-2]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


10

In [11]:
#Slicing
print(b)
print(b[2:8:2])
print(b[3:])
print(b[:])

[11 12 13 14 15 16 17 18 19]
[13 15 17]
[14 15 16 17 18 19]
[11 12 13 14 15 16 17 18 19]


In [12]:
#5 6
#9 10
print(a)
a[1::,1:3:1]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[ 5,  6],
       [ 9, 10]])

In [13]:
a[0:3:1,0:4:2]

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])