<a href="https://colab.research.google.com/github/ultrasmartary/MLCollege/blob/master/MLCollege_Day3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Arithmatic Operations

import numpy as np
a=np.ones((3,3))
print(a)
b=np.arange(5,14)
print(b)
print('\n dimensions of b',b.ndim)
b.shape=(3,3)
print(b)

print('\n a+b:\n',a+b)
print('\n a add b \n',np.add(a,b))

print('\n a-b:\n',a-b)
print('\n a substract b \n',np.subtract(a,b))

print('\n a matrix multiply b \n',np.dot(a,b))

print('\n a multiply b \n',a*b)
print('\n a multiply b \n',np.multiply(a,b))

print('\n a divide b \n',a/b)
print('\n a divide b \n',np.divide(a,b))

In [ ]:
# i*j*k (3*2*4)

a=np.ones((2,3))
print(a.shape)
print('\n a: \n',a)

b=np.arange(0,2)
print(b.shape)
print('\n b: \n',b)

b=b[:, np.newaxis]
print(b.shape)
print('\n b: \n',b)

print(a+b)

In [ ]:
#Transpose

a=np.arange(0,9)
a.shape=(3,3)
print('\n',a)
print('\n',np.transpose(a,axes=(0,1)))
print('\n',np.transpose(a,axes=(1,0)))

In [ ]:
#Combining two arrays

a=np.array([[1,2],[3,4]])
b=np.array([5,6])
c=np.array([[5],[6]])

print('\n a: \n',a)
print('\n b: \n',b)
print('\n c: \n',c)

print('\n vstack \n',np.vstack((a,b)))
print('\n hstack \n',np.hstack((a,c)))

a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]]) 
print('\n concatenate \n',np.concatenate((a,b)))
print('\n concatenate \n',np.concatenate((a,b),axis = 1))

In [ ]:
#Splitting an array

a=np.arange(0,9)
a.shape=(3,3)
print(a)
print(np.split(a,3,axis=1))


[[0 1 2]
 [3 4 5]
 [6 7 8]]
[array([[0],
       [3],
       [6]]), array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]])]


In [ ]:
# Inserting an element in an array

a=np.arange(0,9)
print(a)
np.insert(a,3,-99)
a.shape=(3,3)
print(a)
print(np.insert(a,1,-5))

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[ 0 -5  1  2  3  4  5  6  7  8]


In [ ]:
# Linear Algebra(linalg)

a=np.arange(1,5)
a.shape=(2,2)
print(a)
print(np.linalg.inv(a))
print(np.linalg.matrix_power(a,3))
print(np.linalg.det(a))

In [ ]:
#Solving Algebric expressions

# 3x+y=9
# x+2y=8

a=np.array([[3,1],[1,2]])
print(a)
b=np.array([9,8])
print(b)
np.linalg.solve(a,b)

# 6x+2y-5z=13
#3x+3y-2z=13
#7x+5y-3z=26
a=np.array([[6,2,-5],[3,3,-2],[7,5,-3]])
b=np.array([13,13,26])
np.linalg.solve(a,b)


In [ ]:
a=np.arange(0,9)
a.shape=(3,3)
print(a)
print(np.max(a))
print(np.min(a))
print(np.argmax(a))
print(np.argmin(a))
print(np.mean(a))
print(np.sum(a))
print(np.std(a))

In [ ]:
a = np.arange(0,27)
b = np.arange(0,27)
a.shape=(3,3,3)
b.shape=(3,3,3)
print(np.vstack((a,b)))

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]

 [[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
